version: '3'
services:
  tests:
    build: .
    container_name: e2etests
    volumes:
      - ../test/robot:/test
      - ../results:/test/output
    command: 'robot --outputdir /test/output  /test'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
